[project]
name = "genai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shahab Alam", email = "shahabalam2512@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "langchain>=1.4.0",
    "langchain-groq>=1.1.3",
    "langchain-huggingface>=1.2.2",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.0.1",
    "torch>=2.14.0",
    "transformers>=5.17.0",
    "uvicorn>=0.53.0",
]

[project.scripts]
genai = "genai:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
